import { Resource, MaterialRequest, User } from './types';

export const MOCK_RESOURCES: Resource[] = [
  // --- CSE RESOURCES ---
  {
    id: 'cse-1',
    title: 'Introduction to Algorithms (CLRS) - 3rd Ed',
    type: 'book',
    branch: 'CSE',
    semester: 3,
    subject: 'Algorithms',
    author: 'Cormen, Leiserson, Rivest, Stein',
    downloadUrl: 'https://pdfobject.com/pdf/sample.pdf',
    downloads: 5420,
    likes: 320,
    uploadedBy: 'Admin',
    uploadedAt: '2023-08-15',
    description: 'The definitive guide to algorithms. Essential for placements and GATE.',
    tags: ['Standard Book', 'Algorithms'],
  },
  {
    id: 'cse-2',
    title: 'Operating System Concepts (Galvin) - 10th Ed',
    type: 'book',
    branch: 'CSE',
    semester: 4,
    subject: 'Operating Systems',
    author: 'Silberschatz, Galvin, Gagne',
    downloadUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 4100,
    likes: 250,
    uploadedBy: 'Admin',
    uploadedAt: '2023-08-16',
    description: 'Best book for OS concepts. Covers processes, threads, scheduling, and more.',
  },
  {
    id: 'cse-3',
    title: 'Database System Concepts (Korth) - 6th Ed',
    type: 'book',
    branch: 'CSE',
    semester: 4,
    subject: 'DBMS',
    author: 'Silberschatz, Korth, Sudarshan',
    downloadUrl: '#',
    downloads: 3200,
    likes: 180,
    uploadedBy: 'Admin',
    uploadedAt: '2023-08-20',
  },
  {
    id: 'cse-4',
    title: 'Computer Networks (Tanenbaum) - 5th Ed',
    type: 'book',
    branch: 'CSE',
    semester: 5,
    subject: 'Computer Networks',
    author: 'Andrew S. Tanenbaum',
    downloadUrl: '#',
    downloads: 2800,
    likes: 150,
    uploadedBy: 'Admin',
    uploadedAt: '2023-09-01',
  },
  {
    id: 'cse-5',
    title: 'Handwritten Notes - Data Structures (Unit 1-5)',
    type: 'note',
    branch: 'CSE',
    semester: 3,
    subject: 'Data Structures',
    author: 'Topper Batch 2023',
    downloadUrl: 'https://pdfobject.com/pdf/sample.pdf',
    downloads: 8500,
    likes: 900,
    uploadedBy: 'Rahul Gupta',
    uploadedAt: '2024-01-10',
    tags: ['Handwritten', 'Exam Oriented'],
    description: 'Complete syllabus covered. Very easy to understand.',
  },
  {
    id: 'cse-6',
    title: 'Operating Systems - Last Minute Revision Notes',
    type: 'note',
    branch: 'CSE',
    semester: 4,
    subject: 'Operating Systems',
    author: 'Prep4BTech Team',
    downloadUrl: '#',
    downloads: 1200,
    likes: 130,
    uploadedBy: 'Admin',
    uploadedAt: '2024-04-20',
    tags: ['Short Notes', 'Revision'],
  },
  {
    id: 'cse-7',
    title: 'DBMS End Semester Question Paper 2023',
    type: 'pyq',
    branch: 'CSE',
    semester: 4,
    subject: 'DBMS',
    year: 2023,
    examType: 'Endsem',
    downloadUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    downloads: 900,
    likes: 45,
    uploadedBy: 'ExamCell',
    uploadedAt: '2023-12-15',
  },
  {
    id: 'cse-8',
    title: 'Theory of Computation - Midsem 2023',
    type: 'pyq',
    branch: 'CSE',
    semester: 5,
    subject: 'Theory of Computation',
    year: 2023,
    examType: 'Midsem',
    downloadUrl: '#',
    downloads: 300,
    likes: 15,
    uploadedBy: 'Admin',
    uploadedAt: '2023-10-10',
  },

  // --- ECE RESOURCES ---
  {
    id: 'ece-1',
    title: 'Microelectronic Circuits (Sedra & Smith) - 7th Ed',
    type: 'book',
    branch: 'ECE',
    semester: 3,
    subject: 'Analog Circuits',
    author: 'Sedra & Smith',
    downloadUrl: '#',
    downloads: 3500,
    likes: 210,
    uploadedBy: 'Admin',
    uploadedAt: '2023-08-10',
  },
  {
    id: 'ece-2',
    title: 'Signals and Systems (Oppenheim)',
    type: 'book',
    branch: 'ECE',
    semester: 4,
    subject: 'Signals & Systems',
    author: 'Alan V. Oppenheim',
    downloadUrl: '#',
    downloads: 2800,
    likes: 190,
    uploadedBy: 'Admin',
    uploadedAt: '2023-08-12',
  },
  {
    id: 'ece-3',
    title: 'Digital Electronics - Gate Academy Notes',
    type: 'note',
    branch: 'ECE',
    semester: 3,
    subject: 'Digital Electronics',
    author: 'Gate Academy',
    downloadUrl: '#',
    downloads: 4200,
    likes: 400,
    uploadedBy: 'S. Kumar',
    uploadedAt: '2023-11-05',
    tags: ['GATE', 'High Quality'],
  },

  // --- ME RESOURCES ---
  {
    id: 'me-1',
    title: 'Engineering Thermodynamics (PK Nag)',
    type: 'book',
    branch: 'ME',
    semester: 3,
    subject: 'Thermodynamics',
    author: 'P.K. Nag',
    downloadUrl: '#',
    downloads: 5000,
    likes: 350,
    uploadedBy: 'Admin',
    uploadedAt: '2023-07-20',
  },
  {
    id: 'me-2',
    title: 'Fluid Mechanics (Cengel & Cimbala)',
    type: 'book',
    branch: 'ME',
    semester: 4,
    subject: 'Fluid Mechanics',
    author: 'Cengel',
    downloadUrl: '#',
    downloads: 3100,
    likes: 220,
    uploadedBy: 'Admin',
    uploadedAt: '2023-07-25',
  },
  {
    id: 'me-3',
    title: 'Strength of Materials - Lab Manual',
    type: 'note',
    branch: 'ME',
    semester: 4,
    subject: 'Strength of Materials',
    author: 'Dept of ME',
    downloadUrl: '#',
    downloads: 800,
    likes: 40,
    uploadedBy: 'Lab Assistant',
    uploadedAt: '2023-09-10',
  },

  // --- COMMON / FIRST YEAR ---
  {
    id: 'fy-1',
    title: 'Engineering Mathematics I - B.S. Grewal',
    type: 'book',
    branch: 'CSE', // Often categorized under a branch or General
    semester: 1,
    subject: 'Mathematics I',
    author: 'B.S. Grewal',
    downloadUrl: '#',
    downloads: 10000,
    likes: 800,
    uploadedBy: 'Admin',
    uploadedAt: '2023-07-01',
    description: 'Higher Engineering Mathematics. The goto book for math.',
  },
  {
    id: 'fy-2',
    title: 'Engineering Physics - Notes Unit 1',
    type: 'note',
    branch: 'CSE',
    semester: 1,
    subject: 'Physics',
    author: 'Faculty',
    downloadUrl: '#',
    downloads: 2000,
    likes: 100,
    uploadedBy: 'Admin',
    uploadedAt: '2023-08-01',
  },
];

export const MOCK_REQUESTS: MaterialRequest[] = [
  {
    id: '101',
    topic: 'Compiler Design Last Year Paper',
    type: 'pyq',
    branch: 'CSE',
    semester: 6,
    subject: 'Compiler Design',
    requestedBy: 'Rohan Das',
    requestedAt: '2024-02-18',
    status: 'pending'
  },
  {
    id: '102',
    topic: 'Analog Circuits K.L. Morrison Book',
    type: 'book',
    branch: 'ECE',
    semester: 3,
    subject: 'Analog Circuits',
    requestedBy: 'Sneha P.',
    requestedAt: '2024-02-19',
    status: 'pending'
  },
  {
    id: '103',
    topic: 'Concrete Technology Lab Manual',
    type: 'note',
    branch: 'Civil',
    semester: 4,
    subject: 'Concrete Technology',
    requestedBy: 'Rahul Verma',
    requestedAt: '2024-02-15',
    status: 'fulfilled'
  },
  {
    id: '104',
    topic: 'Automata Theory Ullman Solutions',
    type: 'book',
    branch: 'CSE',
    semester: 5,
    subject: 'Theory of Computation',
    requestedBy: 'Ankit Sharma',
    requestedAt: '2024-02-20',
    status: 'pending'
  }
];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alex Student', email: 'alex@college.edu', role: 'student', branch: 'CSE', semester: 5 },
  { id: 'u2', name: 'Admin User', email: 'admin@college.edu', role: 'admin' },
  { id: 'u3', name: 'Sarah Smith', email: 'sarah@college.edu', role: 'student', branch: 'ECE', semester: 3 },
  { id: 'u4', name: 'Rohan Das', email: 'rohan@college.edu', role: 'student', branch: 'CSE', semester: 6 },
];

export const SUBJECTS_BY_BRANCH: Record<string, string[]> = {
  CSE: [
    'Mathematics I', 'Physics', 'Chemistry', 'Basic Electrical', // 1st Year
    'Data Structures', 'Algorithms', 'Operating Systems', 'DBMS', 'Computer Networks', 
    'Theory of Computation', 'Compiler Design', 'Machine Learning', 'Artificial Intelligence',
    'Computer Organization', 'Discrete Mathematics', 'Software Engineering'
  ],
  ECE: [
    'Mathematics I', 'Physics', 'Basic Electrical',
    'Digital Electronics', 'Signals & Systems', 'Analog Circuits', 'Communication Systems', 
    'Microprocessors', 'Control Systems', 'Network Theory', 'Electromagnetics', 'VLSI Design'
  ],
  ME: [
    'Mathematics I', 'Engineering Mechanics',
    'Thermodynamics', 'Fluid Mechanics', 'Strength of Materials', 'Kinematics', 
    'Heat Transfer', 'Manufacturing Process', 'Theory of Machines', 'IC Engines', 'Industrial Engg'
  ],
  EE: [
    'Mathematics I', 'Basic Electronics',
    'Circuit Theory', 'Control Systems', 'Power Systems', 'Electrical Machines', 
    'Power Electronics', 'Measurements', 'Digital Signal Processing'
  ],
  Civil: [
    'Mathematics I', 'Mechanics',
    'Structural Analysis', 'Geotechnical Engg', 'Fluid Mechanics', 'Surveying', 
    'Concrete Technology', 'Environmental Engg', 'Transportation Engg', 'Hydrology'
  ],
  IT: [
    'Mathematics I', 'Data Structures', 
    'Web Development', 'Software Engineering', 'Information Security', 'Data Mining', 
    'Cloud Computing', 'Mobile Computing', 'Object Oriented Programming'
  ],
};

// Simulation of external resources from prep4btech
export const MOCK_EXTERNAL_RESOURCES: Resource[] = [
    {
        id: 'ext-1',
        title: 'Modern Control Engineering (Ogata) - 5th Ed',
        type: 'book',
        branch: 'EE',
        semester: 5,
        subject: 'Control Systems',
        author: 'Katsuhiko Ogata',
        downloadUrl: 'https://prep4btech.netlify.app/books/control-systems-ogata.pdf',
        downloads: 0,
        likes: 0,
        uploadedBy: 'External',
        uploadedAt: '2024-02-01',
        description: 'Comprehensive treatment of control systems.',
        tags: ['Imported', 'Control Systems']
    },
    {
        id: 'ext-2',
        title: 'Artificial Intelligence: A Modern Approach (Russell & Norvig)',
        type: 'book',
        branch: 'CSE',
        semester: 6,
        subject: 'Artificial Intelligence',
        author: 'Russell & Norvig',
        downloadUrl: 'https://prep4btech.netlify.app/books/ai-russell-norvig.pdf',
        downloads: 0,
        likes: 0,
        uploadedBy: 'External',
        uploadedAt: '2024-02-05',
        description: 'The leading textbook in AI.',
        tags: ['Imported', 'AI']
    },
    {
        id: 'ext-3',
        title: 'Basic Electrical Engineering - V.K. Mehta',
        type: 'book',
        branch: 'EE',
        semester: 1,
        subject: 'Basic Electrical',
        author: 'V.K. Mehta',
        downloadUrl: 'https://prep4btech.netlify.app/books/bee-mehta.pdf',
        downloads: 0,
        likes: 0,
        uploadedBy: 'External',
        uploadedAt: '2024-01-20',
        tags: ['Imported', 'Basic Electrical']
    },
    {
        id: 'ext-4',
        title: 'Software Engineering (Pressman)',
        type: 'book',
        branch: 'CSE',
        semester: 6,
        subject: 'Software Engineering',
        author: 'Roger S. Pressman',
        downloadUrl: 'https://prep4btech.netlify.app/books/se-pressman.pdf',
        downloads: 0,
        likes: 0,
        uploadedBy: 'External',
        uploadedAt: '2024-02-10',
        tags: ['Imported', 'SE']
    },
    {
        id: 'ext-5',
        title: 'Principles of Communication Systems (Taub & Schilling)',
        type: 'book',
        branch: 'ECE',
        semester: 5,
        subject: 'Communication Systems',
        author: 'Taub & Schilling',
        downloadUrl: 'https://prep4btech.netlify.app/books/comms-taub.pdf',
        downloads: 0,
        likes: 0,
        uploadedBy: 'External',
        uploadedAt: '2024-02-12',
        tags: ['Imported', 'Communication']
    }
];